        <ul id="people" class="collection">
          <li class="collection-item avatar">
            <img src="/img/kfarwell.png" alt="kfarwell" class="avatar-img ">
            <span class="title">Kyle Farwell (kfarwell)</span>
            <p>Programmer</p>
            <a href="https://kfarwell.org/" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/fire219.png" alt="fire219" class="avatar-img ">
            <span class="title">Matthew Petry (fire219)</span>
            <p>Artist</p>
            <a href="https://matthew.petrys.net/" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/krourke.png" alt="krourke" class="avatar-img ">
            <span class="title">Keefer Rourke (krourke)</span>
            <p>Programmer</p>
            <a href="https://krourke.org/" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/petvader99.jpg" alt="petvader99" class="avatar-img ">
            <span class="title">Peter Brunner (petvader99)</span>
            <p>Artist</p>
            <a href="http://devpost.com/peterbrunner" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/squid.jpg" alt="squid" class="avatar-img ">
            <span class="title">Phil St. Antoine (squid)</span>
            <p>Designer</p>
            <a href="https://phil.guhnoo.org/" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/jstep33.jpg" alt="jstep33" class="avatar-img ">
            <span class="title">Jared Stephens (jstep33)</span>
            <p>Designer</p>
            <a href="https://github.com/JStephens33" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/iam.png" alt="iam" class="avatar-img ">
            <span class="title">Ace Parent (iam)</span>
            <p>Programmer</p>
            <a href="http://git.starcatcher.us/iam/" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <span class="title">Mustafa Abdul Razzaq</span>
            <p>Programmer</p>
            <a href="https://mustafa.kotori.me/" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <span class="title">Matthew Rose</span>
            <p>Artist</p>
          </li>
          <li class="collection-item avatar">
            <span class="title">Katie Horne</span>
            <p>Artist</p>
          </li>
          <li class="collection-item avatar">
            <img src="/img/you.png" alt="you" class="avatar-img ">
            <span class="title">You?</span>
            <p>Contribute!</p>
            <a href="/contribute" class="secondary-content"><i class="mdi mdi-send"></i></a>
          </li>
        </ul>
